name: Teamspeak verifier
author: Mauricius17
version: 2.3
depend: [UUIDProvider]
main: de.mauricius17.teamspeak.verifier.system.TeamSpeakVerifier
 
commands:
  teamspeak:
    description: TeamSpeak commands
    usage: /teamspeak
    aliases: [ts]

permissions:
  teamspeak.verifier.add:
    default: true
  teamspeak.verifier.remove:
    default: true
  teamspeak.verifier.list:
    default: true